name: Infinite Futures
favicon: null
layout_spectrum: 0.04205768019892275
typography_spectrum: 0.4818850092124194
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.2689899974502623
  lightness: 0.24123496911488473
  saturation: 0.0012833233922719955
  rhythmicContrast: 0.48847552365623415
purpose: []
