name: Infinite Futures
favicon: null
layout_spectrum: 1
typography_spectrum: 0.76418
title: Infinite Futures
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020622'
    - '#15327f'
    - '#94fcfd'
    - '#3057b5'
    - '#859efa'
  brandStrength: 0
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 1
purpose: []
